name: "Run Tests"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
        laravel: [6.*, 7.*, 8.*,9.*]
        include:
          - laravel: 6.*
            testbench: 4.*
            phpunit: ^8.0
          - laravel: 7.*
            testbench: 5.*
            phpunit: ^8.4
          - laravel: 8.*
            testbench: 6.*
            phpunit: ^8.5
          - laravel: 9.*
            testbench: 6.*
            phpunit: ^9.0
        exclude:
          - laravel: 6.*
            php: 7.1
          - laravel: 6.*
            php: 8.1
          - laravel: 7.*
            php: 7.1
          - laravel: 7.*
            php: 8.1
          - laravel: 8.*
            php: 7.1
          - laravel: 8.*
            php: 7.2
          - laravel: 8.*
            php: 7.3
          - laravel: 9.*
            php: 7.1
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4





    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update  --dev
          composer update --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml